### PR TITLE
Fixed broken exception handling (err was missing)

### PR DESCRIPTION
**Pull request by WoLpH**
The `_handle_exception` method was missing `err` which it was still using. This allows support for both

### CODE REVIEW

**Comment by zxdavb** [comment]
Good spot.  What happened that you needed to look at it?

This part of the component needs a full rewrite, but I have been focusing on the official component.  In fact, the whole things needs a tidy up, but all my efforts have been on the official version.

Will just need to test it, then can accept.

**Comment by WoLpH** [comment]
I'm not entirely sure honestly, I simply noticed the stacktrace in the logs and decided to fix it.

So far this module has been working great for me, the only issue I have is that if fails to initialize because I was restarting hass too often (which happens often during developing) it will never recover. So that could be related to the trace as well.

**Comment by zxdavb** [comment]
I'm getting an API limit exceeded (HTTP_TOO_MANY_REQUESTS) during the initialization (i.e. login to Honeywell's web servers) during development too.

It is a little odd though - if you immediately restart, it goes through OK!

**Comment by zxdavb** [comment]
Hey @WoLpH, thanks for your PR, but have made more substantial changes instead.

Nothing wrong with your PR - but my code really was a bit messy there, and you prompted me to clean it up a bit - have a look, and tell be what you think!

**Comment by WoLpH** [comment]
Yes, much improved!

**Pull request closed without merging**
