### PR TITLE
Fixed compatibility with hass 0.89

### PR DESCRIPTION
**Pull request by WoLpH**
This fix enabled hass 0.89 support while still maintaining 0.88 support :)

### CODE REVIEW

**Comment by WoLpH** [comment]
No worries about the conflicts, I'm rebasing it right now :)

**Comment by WoLpH** [comment]
Oh, nevermind. You've fixed it already it seems :)

**Comment by zxdavb** [comment]
Actually, I should have done it your way about 3-4 weeks ago!

**Comment by WoLpH** [comment]
In that case my local git repo was showing me the wrong thing. My bad :P

I did a `git fetch --all` and `git reset --hard origin/master` with a `git clean -dfx` but it wouldn't work in 0.89 for me. Odd... I can't think of a reason why it was using old code in that case.

**Pull request closed without merging**
